plugins: []  # keep default (no extra plugins on Pages)
sass:
  style: compressed
include:
  - assets
defaults:
  - scope: {path: ""} 
    values: {css: "/assets/css/custom.css"}
theme: jekyll-theme-cayman
title: MycoHub
description: Gourmet mushroom cultivation guides
